### ISSUE TITLE
Port to OCaml 5

### ISSUE THREAD

**Issue by mjambon** [rgrinberg/ocaml-semver#4]
This is work in progress at https://github.com/rgrinberg/ocaml-semver/pull/3

**Comment by mjambon** [comment]
Done by #3

**Comment by mjambon** [comment]
@rgrinberg I can handle the opam release if you'd like. Can you please merge https://github.com/rgrinberg/ocaml-semver/pull/6

**Comment by rgrinberg** [comment]
Your help would be appreciated.
